server:
  port: ${PORT:8761}
    
application:
  name: clinic-discovery-service

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
